### ISSUE TITLE
How to play sounds in my spritewidget project？

### ISSUE THREAD

**Issue by pp126** [spritewidget/spritewidget#16]
I didn't find a way to play the sound.

**Comment by ngocdaothanh** [comment]
The example project [spaceblast](https://github.com/spritewidget/spaceblast) contains [sound files](https://github.com/spritewidget/spaceblast/tree/master/assets), but when I play it on my iPhone, there's no sound. Maybe the sound feature is not completed yet.

**Comment by smrucv** [comment]
Hi,

I uncommented all sound-related code lines on SpaceBlast and i got that some classes doesn't exist. Researching a little I found they are part of flutter_sprites package.  I added it as a dependency but I got errors because it already is a dependency for SpriteWidget.

What should I do?

Thanks

**Comment by smrucv** [comment]
I found that Flutter_Sprites is Dart 2 incompatible, thats why sound isn't working.

**Comment by vlidholt** [comment]
Sounds are not part of SpriteWidget itself, but there are many other packages that handle sounds.
