### ISSUE TITLE
It's dead, Jim

### ISSUE THREAD

**Issue by TheKashe** [spritewidget/spritewidget#57]
It seems that Victor left google in 2016 and has since almost stopped supporting this project and Google seems to not invest into it anymore.

There are some stupid bugs like the 180.8 one in convreting deg->rad. There are also some other issues, like spriteBox not being propagated below the first level of root node children. I also feel like state management is missing / current way of handling root node goes against flutter stateless design etc...

The biggest obstacle I see for forking is a lack of official license. Although, the pub.dev page lists Victor as author (but if he worked for Google at the time Google probably owns the IP) and BSD as license. I guess we could seek clarification through Victor / flutter team.

Is there anyone interesting in contributing to a fork?

**Comment by dsyrstad** [comment]
I'm currently working on a private fork to reintroduce sound support and SVG, Picture, and Flare nodes. Regarding the license, it seems to have a LICENSE file, so I think we're good there. It was originally based on https://pub.dev/packages/flutter_sprites which was produced by the Flutter/Google team. It goes way back to https://github.com/raju-bitter/flutter_sprites AFAICT.

**Comment by vlidholt** [comment]
Hey guys, I'm running my own startup which takes most of my time, but planning on taking some time to make sure everything is up-to-date.

**Comment by i-schuetz** [comment]
Any news? :/

**Comment by dsyrstad** [comment]
@i-schuetz I still have a private fork and it is working for one of my games. I've also created a port of the Flint particle system as an extension module. I'm a little concerned about supporting both projects in a timely manner if I open them up. If anything the fork would become it's own project because it has departed a bit from this project's API.

I have a major backlogged item to address battery performance because spritewidget currently repaints on every frame. It should only process updates on every frame and if something has changed, repaint.

**Comment by TheKashe** [comment]
@dsyrstad would you care to make your fork public? It makes no sense for all of us to maintain their own copies.

**Comment by ponderMuse** [comment]
I've been playing around with SpriteWidget and I have been really impressed with how well it seemed to worked with Flutter generally but I am now starting to encounter problems when doing something simple like trying to set `userInteractionEnabled = true;` on `Node`s in order to handle click events but, this feature doesn't seem to work in Nodes other than the root Node in a tree from what I can see.

I can see that there have been similar issues raised for this event handling issue but no progress seems to have been made on them.

Is this project now well and truly dead? What other alternatives have people been looking at as a replacement for this project if there are any alternatives out there at all?

Thanks in advance,
PM

**Comment by dsyrstad** [comment]
@TheKashe @ponderMuse I would like to make my fork public, but I currently cannot take on the effort to support it. I have numerous enhancements, including Lottie support, SVG support, a port of the Flint Particle System, and null-safety. I also have more than I'm working on - I'm (slowly) working on a port of game from the Android SDK/OpenGL ES currently. I'm thinking that sometime in August or September 2021, I can make it public.

**Comment by mjaffa-figure** [comment]
@dsyrstad Any status on opening up your Fork?

**Comment by mjaffa-figure** [comment]
@dsyrstad do you think it would be easy to add Animated gifs as a Sprite node on your fork? my own fork works good enough for me for now. But I need animated gif support for Sprites. I don't want to have to cut the animated gif up, just want it as it displayed in a Sprite and it animate on its own.

**Comment by dsyrstad** [comment]
@mjaffa-figure I have integrated Lottie and Rive animations - it might be more attractive and more controllable to use them than an animated gif. I could make my fork public, but it will in "it works for me" shape. I'll look at pushing it this weekend. It will likely just be a separate repo, not a fork.

**Comment by Birand01** [comment]
Guys who are you? why am ı getting these irrelevant emails?

Dan Syrstad ***@***.***>, 20 Nis 2022 Çar, 00:30 tarihinde
şunu yazdı:

**Comment by dsyrstad** [comment]
> Guys who are you? why am ı getting these irrelevant emails? 

Perhaps you're subscribed to this issue?

**Comment by mjaffa-figure** [comment]
@dsyrstad awesome, thanks! I look forward to that separate repo and will look into seeing the effort on converting these animated gifs into Lotties so I can just use what you got.

**Comment by vlidholt** [comment]
It's back alive! 2.0 release coming very soon! 🥳

**Comment by dsyrstad** [comment]
@vlidholt @mjaffa-figure @ponderMuse @TheKashe Here is my "fork" of spritewidget, along with my port of the Flint particle system: https://github.com/SyriousGames/EspritWidget. If you can make use of it, great, but I cannot provide a lot of support at this time.
